### ISSUE TITLE
create a login_form

### ISSUE THREAD

**Issue by allensphilip** [allensphilip/WEB-DEV-ONE-PAGE#2]

**Comment by Dhanunjay18** [comment]
Please assign this issue to me

**Comment by Anisha-012** [comment]
Hey @allensphilip! I would love to work on this issue. Could you please assign this issue to me?

**Comment by Prakhar9450** [comment]
Please assign me this issue

**Comment by allensphilip** [comment]
@Anisha-012 @Dhanunjay18 @Prakhar9450 
Happy dev hours🍃

**Comment by allensphilip** [comment]
Done
